name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Deno environment
        uses: denoland/setup-deno@v1

      - name: Deno Fmt Check
        run: deno fmt --check

      - name: Deno Lint Check
        run: deno lint

      - name: Deno Test
        run: deno test --allow-env --allow-read
